url: https://helix-origin.github.io
baseurl: /Windhawk-Themes
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: documentation
relative_links:
  enabled: true
optional_front_matter:
  remove_originals: true
